[project]
authors = ["Marc Schneider marc@shnei.de"]
description = "Python Boilerplate"
name = "python_boilerplate"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]
main = "python -m python_boilerplate"

[pypi-dependencies]
python_boilerplate = { path = ".", editable = true }

[dependencies]
python = ">=3.11,<4"
pyyaml = "*"
python-dotenv = "*"
loguru = "*"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest tests/"

[feature.lint.dependencies]
ruff = "*"

[feature.lint.tasks]
lint = "ruff check --fix ."

[environments]
default = { features = ["test", "lint"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
prod = { features = [], solve-group = "default" }
